





























# This is a basic workflow to help you get started with Actions

name: v1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the live branch
  push:
    branches: live

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout this repo
        uses: actions/checkout@v3
        with:
          path: toolkit
      - name: checkout dest repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DESTINATION_REPOSITORY }}
          path: dest

      # Runs a single command using the runners shell
      - name: pack and copy
        run: |
          cd $GITHUB_WORKSPACE/toolkit/server/v1
          ./download.sh
          ./pack.sh
          cp packed.zip ../../../dest
      # Runs a set of commands using the runners shell
      - name: commit
        run: |
          cd $GITHUB_WORKSPACE/dest
          git commit -m "$(TZ='Asia/Tokyo' date +%Y-%m-%d_%H.%M.%S) update"
          git push "https://github-actions:${{ secrets.PAT }}@github.com/repo.git"











































